[pytest]
minversion = 7.0
pythonpath = .
testpaths = tests
filterwarnings =
	ignore:Airflow currently can be run on POSIX-compliant Operating Systems.:RuntimeWarning
addopts = --cov=dags --cov-report=term-missing