from typing import Any
from datetime import timedelta
from dateutil.relativedelta import relativedelta

from dag_xflow_nexus_hjaelpemidler.constants import *
from dag_xflow_nexus_hjaelpemidler.forms import *

FORM_CONFIG_BY_TABLE: dict[str, dict[str, Any]] = {
    "personligt_hjaelpemiddel": {
        "dashboard_name": ASSISTIVE_DEVICES_DASHBOARD_NAME,
        "document_widget_name": ASSISTIVE_DEVICES_DOCUMENT_WIDGET_NAME,
        "form_widget_name": ASSISTIVE_DEVICES_FORM_WIDGET_NAME,
        "form_name": ASSISTIVE_DEVICES_FORM_NAME,
        "program_name": TOP_PROGRAM_NAME,
        "pathway_name": ASSISTIVE_DEVICES_PATHWAY,
        "generate_assignment_title": lambda model_object: f"{model_object.device_name.strip() or 'Personligt hjælpemiddel'} {model_object.renewal_or_new_text}",
        "generate_due_date": lambda model_object: model_object.form_date + timedelta(weeks=30),
        "generate_extended_due_date": lambda model_object: None,
        "assignment_name": ASSISTIVE_DEVICES_ASSIGNMENT_NAME,
        "assignment_organization": ASSISTIVE_DEVICES_GROUP_NAME,
        "error_notification_recipient": "personligehjaelpemidler@randers.dk",
    },
    "servicehund": {
        "dashboard_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_DASHBOARD_NAME,
        "document_widget_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_DOCUMENT_112_113_WIDGET_NAME,
        "form_widget_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_FORM_112_113_WIDGET_NAME,
        "form_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_112_113_FORM_NAME,
        "program_name": TOP_PROGRAM_NAME,
        "pathway_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_112_113_PATHWAY,
        "generate_assignment_title": lambda model_object: f"{model_object.device_name.strip() or 'Servicehund'} {model_object.renewal_or_new_text}",
        "generate_due_date": lambda model_object: model_object.form_date + timedelta(weeks=30),
        "generate_extended_due_date": lambda model_object: model_object.form_date + timedelta(weeks=48),
        "assignment_name": ASSISTIVE_TECHNOLOGY_ASSIGNMENT_NAME,
        "assignment_organization": ASSISTIVE_TECHNOLOGY_GROUP_NAME,
        "error_notification_recipient": "hjaelpemiddelvisitator@randers.dk",
    },
    "kommunikationshjælpemiddel": {
        "dashboard_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_DASHBOARD_NAME,
        "document_widget_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_DOCUMENT_112_113_WIDGET_NAME,
        "form_widget_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_FORM_112_113_WIDGET_NAME,
        "form_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_112_113_FORM_NAME,
        "program_name": TOP_PROGRAM_NAME,
        "pathway_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_112_113_PATHWAY,
        "generate_assignment_title": lambda model_object: f"{model_object.device_name.strip() or 'Kommunikationshjælpemiddel'} {model_object.renewal_or_new_text}",
        "generate_due_date": lambda model_object: model_object.form_date + timedelta(weeks=30),
        "generate_extended_due_date": lambda model_object: model_object.form_date + timedelta(weeks=48),
        "assignment_name": ASSISTIVE_TECHNOLOGY_ASSIGNMENT_NAME,
        "assignment_organization": ASSISTIVE_TECHNOLOGY_GROUP_NAME,
        "error_notification_recipient": "hjaelpemiddelvisitator@randers.dk",
    },
    "hjaelpemiddel_til_barn": {
        "dashboard_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_DASHBOARD_NAME,
        "document_widget_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_DOCUMENT_112_113_WIDGET_NAME,
        "form_widget_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_FORM_112_113_WIDGET_NAME,
        "form_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_112_113_FORM_NAME,
        "program_name": TOP_PROGRAM_NAME,
        "pathway_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_112_113_PATHWAY,
        "generate_assignment_title": lambda model_object: f"{model_object.device_name.strip() or 'Hjælpemiddel til barn'} {model_object.renewal_or_new_text}",
        "generate_due_date": lambda model_object: model_object.form_date + timedelta(weeks=30),
        "generate_extended_due_date": lambda model_object: model_object.form_date + timedelta(weeks=48),
        "assignment_name": ASSISTIVE_TECHNOLOGY_ASSIGNMENT_NAME,
        "assignment_organization": ASSISTIVE_TECHNOLOGY_GROUP_NAME,
        "error_notification_recipient": "hjaelpemiddelvisitator@randers.dk",
    },
    "hjaelpemiddel_andre_typer_af_hjaelpemidler": {
        "dashboard_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_DASHBOARD_NAME,
        "document_widget_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_DOCUMENT_112_113_WIDGET_NAME,
        "form_widget_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_FORM_112_113_WIDGET_NAME,
        "form_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_112_113_FORM_NAME,
        "program_name": TOP_PROGRAM_NAME,
        "pathway_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_112_113_PATHWAY,
        "generate_assignment_title": lambda model_object: f"{model_object.device_name.strip() or 'Andre typer af hjælpemidler'} {model_object.renewal_or_new_text}",
        "generate_due_date": lambda model_object: model_object.form_date + timedelta(weeks=30),
        "generate_extended_due_date": lambda model_object: model_object.form_date + timedelta(weeks=48),
        "assignment_name": ASSISTIVE_TECHNOLOGY_ASSIGNMENT_NAME,
        "assignment_organization": ASSISTIVE_TECHNOLOGY_GROUP_NAME,
        "error_notification_recipient": "hjaelpemiddelvisitator@randers.dk",
    },
    "staastoettestol": {
        "dashboard_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_DASHBOARD_NAME,
        "document_widget_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_DOCUMENT_112_113_WIDGET_NAME,
        "form_widget_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_FORM_112_113_WIDGET_NAME,
        "form_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_113_FORM_NAME,
        "program_name": TOP_PROGRAM_NAME,
        "pathway_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_113_PATHWAY,
        "generate_assignment_title": lambda model_object: f"{model_object.device_name.strip() or 'Ståstøttestol'} {model_object.renewal_or_new_text}",
        "generate_due_date": lambda model_object: model_object.form_date + timedelta(weeks=30),
        "generate_extended_due_date": lambda model_object: model_object.form_date + timedelta(weeks=48),
        "assignment_name": ASSISTIVE_TECHNOLOGY_ASSIGNMENT_NAME,
        "assignment_organization": ASSISTIVE_TECHNOLOGY_GROUP_NAME,
        "error_notification_recipient": "hjaelpemiddelvisitator@randers.dk",
    },
    "elscooter": {
        "dashboard_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_DASHBOARD_NAME,
        "document_widget_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_DOCUMENT_112_113_WIDGET_NAME,
        "form_widget_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_FORM_112_113_WIDGET_NAME,
        "form_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_113_FORM_NAME,
        "program_name": TOP_PROGRAM_NAME,
        "pathway_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_113_PATHWAY,
        "generate_assignment_title": lambda model_object: f"{model_object.device_name.strip() or 'Elscooter'} {model_object.renewal_or_new_text}",
        "generate_due_date": lambda model_object: model_object.form_date + timedelta(weeks=30),
        "generate_extended_due_date": lambda model_object: model_object.form_date + timedelta(weeks=48),
        "assignment_name": ASSISTIVE_TECHNOLOGY_ASSIGNMENT_NAME,
        "assignment_organization": ASSISTIVE_TECHNOLOGY_GROUP_NAME,
        "error_notification_recipient": "hjaelpemiddelvisitator@randers.dk",
    },
    "stoette_til_bil": {
        "dashboard_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_DASHBOARD_NAME,
        "document_widget_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_DOCUMENT_114_WIDGET_NAME,
        "form_widget_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_FORM_114_WIDGET_NAME,
        "form_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_FORM_114_FORM_NAME,
        "program_name": TOP_PROGRAM_NAME,
        "pathway_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_114_PATHWAY,
        "generate_assignment_title": lambda model_object: f"{model_object.device_name.strip() or 'Støtte til bil'} {model_object.renewal_or_new_text}",
        "generate_due_date": lambda model_object: model_object.form_date + timedelta(weeks=30),
        "generate_extended_due_date": lambda model_object: model_object.form_date + timedelta(weeks=58),
        "assignment_name": ASSISTIVE_TECHNOLOGY_ASSIGNMENT_NAME,
        "assignment_organization": ASSISTIVE_TECHNOLOGY_GROUP_NAME,
        "error_notification_recipient": "hjaelpemiddelvisitator@randers.dk",
    },
    "saerlig_indretning_af_bil_koerekort": {
        "dashboard_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_DASHBOARD_NAME,
        "document_widget_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_DOCUMENT_114_WIDGET_NAME,
        "form_widget_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_FORM_114_WIDGET_NAME,
        "form_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_FORM_114_FORM_NAME,
        "program_name": TOP_PROGRAM_NAME,
        "pathway_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_114_PATHWAY,
        "generate_assignment_title": lambda model_object: f"{model_object.device_name.strip() or 'Særlig indretning af bil'} {model_object.renewal_or_new_text}",
        "generate_due_date": lambda model_object: model_object.form_date + timedelta(weeks=30),
        "generate_extended_due_date": lambda model_object: model_object.form_date + timedelta(weeks=58),
        "assignment_name": ASSISTIVE_TECHNOLOGY_ASSIGNMENT_NAME,
        "assignment_organization": ASSISTIVE_TECHNOLOGY_GROUP_NAME,
        "error_notification_recipient": "hjaelpemiddelvisitator@randers.dk",
    },
    "boligindretning": {
        "dashboard_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_DASHBOARD_NAME,
        "document_widget_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_DOCUMENT_116_WIDGET_NAME,
        "form_widget_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_FORM_116_WIDGET_NAME,
        "form_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_FORM_116_FORM_NAME,
        "program_name": TOP_PROGRAM_NAME,
        "pathway_name": ASSISTIVE_TECHNOLOGY_ASSESSMENT_116_PATHWAY,
        "generate_assignment_title": lambda model_object: f"{model_object.device_name.strip() or 'Boligindretning'} {model_object.renewal_or_new_text}",
        "generate_due_date": lambda model_object: model_object.form_date + relativedelta(months=12),
        "generate_extended_due_date": lambda model_object: model_object.form_date + relativedelta(months=20),
        "assignment_name": ASSISTIVE_TECHNOLOGY_ASSIGNMENT_116_NAME,
        "assignment_organization": ASSISTIVE_TECHNOLOGY_GROUP_NAME,
        "error_notification_recipient": "hjaelpemiddelvisitator@randers.dk",
    }
}

build_fields_by_table = {
    "personligt_hjaelpemiddel": generate_personligt_hjaelpemiddel_fields,
    "staastoettestol": generate_staastoettestol_fields,
    "saerlig_indretning_af_bil_koerekort": generate_saerlig_indretning_af_bil_koerekort_fields,
    "boligindretning": generate_boligindretning_fields,
    "stoette_til_bil": generate_stoette_til_bil_fields,
    "elscooter": generate_elscooter_fields,
    "hjaelpemiddel_til_barn": generate_hjaelpemiddel_til_barn_fields,
    "kommunikationshjælpemiddel": generate_kommunikationshjaelpemiddel_fields,
    "servicehund": generate_servicehund_fields,
    "hjaelpemiddel_andre_typer_af_hjaelpemidler": generate_andre_typer_af_hjaelpemidler_fields,
}
