name: Build and Redeploy

on:
  push:
    branches:
      - test
      - staging
      - prod
    paths:
      - Dockerfile
      - requirements.txt

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set lowercase repository name
        id: repo
        run: echo "repo=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ env.repo }}:${{ github.ref_name }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-publish
    steps:

      - name: Checkout Target Repository
        id: checkout
        uses: actions/checkout@v4
        with:
          repository: Randers-Kommune-Digitalisering/kithosting-randers-kommune-apps
          ref: ${{ github.ref_name }}
          path: infrastructure
          ssh-key: ${{ secrets.AUTO_DEPLOY }}

      - name: Install yq
        run: |
          sudo apt install -y jq
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.40.5/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Update redeployTimestamp
        id: redeployupdate
        run: |
          timestamp=$(date +'%Y-%m-%dT%H:%M')
          yq e ".airflow.redeployTimestamp = \"$timestamp\"" -i infrastructure/airflow/values.yaml

      - name: Commit and push
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          cd infrastructure
          if [[ -n "$(git status -s)" ]]; then
            git commit -am "Update redeployTimestamp"
            git push
