SENSUM_CONFIG = [
    {
        "name": "aktive_indsatser",
        "patterns": ["Indsatser_*.csv"],
        "group_by": "IndsatsId",
        "directories": ["/D:/SFTP-EGDW/sensum_randers"],
        "agg_columns": {
            "IndsatsStartDato": "first",
            "IndsatsStatus": "first",
            "IndsatsSlutDato": "first",
        },
        "columns": ["IndsatsStartDato", "IndsatsStatus", "IndsatsSlutDato"],
        "merge_func": "process_indsats_df",
    },
    {
        "name": "aktive_sager",
        "patterns": ["Sager_*.csv", "Afdeling_*.csv", "Medarbejder_*.csv"],
        "group_by": "SagId",
        "directories": ["/D:/SFTP-EGDW/sensum_randers"],
        "agg_columns": {
            "SagNavn": "first",
            "SagType": "first",
            "MedarbejderFornavn": "first",
            "MedarbejderEfternavn": "first",
            "AfdelingNavn": "first",
            "Status": "first",
        },
        "columns": [
            "SagNavn",
            "SagType",
            "MedarbejderFornavn",
            "MedarbejderEfternavn",
            "AfdelingNavn",
            "Status",
        ],
        "merge_func": "sager_afdeling_medarbejder_merge_df",
    }
    # {
    #     "name": "ydelse",
    #     "patterns": ["Ydelse_*.csv", "Afdeling_*.csv"],
    #     "group_by": "YdelseId",
    #     "directories": ["/D:/SFTP-EGDW/Frem"],
    #     "agg_columns": {
    #         "YdelseNavn": "first",
    #         "StartDato": "first",
    #         "SlutDato": "first",
    #         "Navn": "first",
    #     },
    #     "columns": ["YdelseNavn", "StartDato", "SlutDato", "AfdelingNavn"],
    #     "merge_func": "merge_df_ydelse",
    # },
    # {
    #     "name": "indsats_fordeling",
    #     "patterns": ["Sager_*.csv", "Indsatser_*.csv"],
    #     "merge_on": "SagId",
    #     "group_by": "IndsatsId",
    #     "directories": ["/D:/SFTP-EGDW/sensum_randers"],
    #     "agg_columns": {
    #         "IndsatsStatus": "first",
    #         "Indsats": "first",
    #         "AfdelingNavn": "first",
    #         "IndsatsStartDato": "first",
    #         "IndsatsSlutDato": "first",
    #         "LeverandørIndsats": "first",
    #         "LeverandørNavn": "first",
    #         "IndsatsParagraf": "first",
    #     },
    #     "columns": [
    #         "IndsatsStatus",
    #         "Indsats",
    #         "AfdelingNavn",
    #         "IndsatsStartDato",
    #         "IndsatsSlutDato",
    #         "LeverandørIndsats",
    #         "LeverandørNavn",
    #         "IndsatsParagraf",
    #     ],
    #     "merge_func": "merge_dataframes",
    # },
]
